openapi: '3.0.1'
info:
  title: Chat App API
  version: 1.0.0
  description: A documentation for chat app
components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT
servers:
  - url: https://localhost:8080/api/v1
paths:
  /auth/verify:
    $ref: './paths/auth/verify.path.yaml'
  /user/self:
    $ref: './paths/user/self.path.yaml'