openapi: '3.0.0'
info:
  title: Chat App API
  version: 1.0.0
  description: A documentation for chat app
components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT
servers:
  - url: http://localhost/api/v1
  - url: https://localhost/api/v1
paths:
  /auth/verify:
    $ref: './paths/auth/verify.path.yaml'
  /auth/forgot-password:
    $ref: './paths/auth/forgot_password.path.yaml'
  /auth/reset-password:
    $ref: './paths/auth/reset_password.path.yaml'
  /user/self:
    $ref: './paths/user/self.path.yaml'
  /user/verify-email:
    $ref: './paths/user/verify_email.path.yaml'
  /user/search:
    $ref: './paths/user/search.path.yaml'
  /user/{id}:
    $ref: './paths/user/id.path.yaml'
  /friend:
    $ref: './paths/friend/index.path.yaml'
  /friend/friend-requests:
    $ref: './paths/friend/friend-requests.path.yaml'
  /friend/{id}:
    $ref: './paths/friend/id.path.yaml'
  /friend/friend-requests-sent:
    $ref: './paths/friend/friend-requests-sent.path.yaml'
  /friend/friend-requests-sent/{id}:
    $ref: './paths/friend/friend-requests-sent.id.path.yaml'
  /chat-room:
    $ref: './paths/chat/index.path.yaml'
  /chat-room/{chatRoomId}/accept:
    $ref: './paths/chat/chat-room-id.accept.yaml'
  /chat-room/{chatRoomId}/reject:
    $ref: './paths/chat/chat-room-id.reject.yaml'
  /chat-room/{chatRoomId}:
    $ref: './paths/chat/chat-room-id.path.yaml'
  /chat-room/{chatRoomId}/{memberId}:
    $ref: './paths/chat/chat-room-id.member-id.path.yaml'
  /chat-room/chat-room-requests:
    $ref: './paths/chat/chat-room-requests.yaml'
  /admin/user/{userId}:
    $ref: './paths/admin/user.path.yaml'
  /admin/user/seed:
    $ref: './paths/admin/seed.path.yaml'
  /message/chat-room/{chatRoomId}:
    $ref: './paths/message/chat-room.id.path.yaml'
