openapi: '3.0.0'
info:
  title: Chat App API
  version: 1.0.0
  description: A documentation for chat app
components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SystemMessageType:
      $ref: './components/models/system-message-type.component.yaml#/schemas/SystemMessageType'
servers:
  - url: http://localhost/api/v1
  - url: https://localhost/api/v1
paths:
  /auth/verify:
    $ref: './paths/auth/verify.path.yaml'
  /auth/forgot-password:
    $ref: './paths/auth/forgot_password.path.yaml'
  /auth/reset-password:
    $ref: './paths/auth/reset_password.path.yaml'
  /user/self:
    $ref: './paths/user/self.path.yaml'
  /user/verify-email:
    $ref: './paths/user/verify_email.path.yaml'
  /user/search:
    $ref: './paths/user/search.path.yaml'
  /user/{id}:
    $ref: './paths/user/id.path.yaml'
  /friend:
    $ref: './paths/friend/index.path.yaml'
  /friend/friend-requests:
    $ref: './paths/friend/friend-requests.path.yaml'
  /friend/{id}:
    $ref: './paths/friend/id.path.yaml'
  /friend/friend-requests-sent:
    $ref: './paths/friend/friend-requests-sent.path.yaml'
  /friend/friend-requests-sent/{id}:
    $ref: './paths/friend/friend-requests-sent.id.path.yaml'
  /chat-room:
    $ref: './paths/chat/index.path.yaml'
  /chat-room/{chatRoomId}/accept:
    $ref: './paths/chat/chat-room-id.accept.yaml'
  /chat-room/{chatRoomId}/reject:
    $ref: './paths/chat/chat-room-id.reject.yaml'
  /chat-room/{chatRoomId}/leave:
    $ref: './paths/chat/chat-room-id.leave.yaml'
  /chat-room/{chatRoomId}:
    $ref: './paths/chat/chat-room-id.path.yaml'
  /chat-room/{chatRoomId}/{memberId}:
    $ref: './paths/chat/chat-room-id.member-id.path.yaml'
  /chat-room/chat-room-requests:
    $ref: './paths/chat/chat-room-requests.yaml'
  /chat-room/chat-room-requests-sent:
    $ref: './paths/chat/chat-room-requests-sent.path.yaml'
  /chat-room/chat-room-requests-sent/{chatRoomId}/{friendId}:
    $ref: './paths/chat/chat-room-requests-sent.chat-room-id.friend-id.path.yaml'
  /admin/user/{userId}:
    $ref: './paths/admin/user.path.yaml'
  /admin/user/seed:
    $ref: './paths/admin/seed.path.yaml'
  /message/chat-room/{chatRoomId}:
    $ref: './paths/message/chat-room.id.path.yaml'
  /message/{messageId}:
    $ref: './paths/message/id.path.yaml'
  /notification:
    $ref: './paths/notification/index.path.yaml'
  /notification/{notificationId}:
    $ref: './paths/notification/id.path.yaml'
  /search:
    $ref: './paths/search/index.path.yaml'
  /device:
    $ref: './paths/device/index.path.yaml'
  /device/{id}:
    $ref: './paths/device/id.path.yaml'
  /webrtc/{id}:
    $ref: './paths/webrtc/id.path.yaml'

  