version: '3.9'
services:
  server:
    build:
      dockerfile: Dockerfile.server
      context: .
    env_file:
      - .env
    networks:
      - chat_app_server
networks:
  chat_app_server:
    name: doan1
